<div class="s-prose s-prose__disable-spoiler-hover js-post-body" itemprop="text">
<p>In the case that the error code is not 11000 I would re-throw the error in the inner try. That way you do not repeat, possibly complex error logic or possibly execute code that you do not want to. i.e. instead of </p>

<pre><code>try {
  try {
    // code
  } catch(err) {
    if (err.code === 11000) { 
      log({completed: err.result.nInserted, duplicates: err.result.result.writeErrors.length})
    } else { 
      log('an error occurred', {err} )
    }
  }
  //code that shouldn't execute when an error occurs
} catch(err) {
  log('an error occurred', {err} )
}
</code></pre>

<p>something like</p>

<pre><code>try {
  try {
    // code
  } catch(err1) {
    if (err1.code !== 11000) {
      throw err1;
    } 
    log({completed: err1.result.nInserted, duplicates: err1.result.result.writeErrors.length})
  }
  //code that shouldn't execute when an error occurs
} catch(err2) {
  log('an error occurred', {err2} )
}
</code></pre>

<p>I also suggest using different variable names in different exception handlers. Some spaces between parentheses and curly brackets would also make your code more readable.</p>
    </div>