<div class="s-prose s-prose__disable-spoiler-hover js-post-body" itemprop="text">
<p>This error handling looks pretty useless to me:</p>

<ul>
<li>The log message doesn't record which URL was inaccessible.</li>
<li>If an error occurs, then the code will continue to execute. That means that whoever calls this function will have to handle the possibility of a <code>null</code> result. If that isn't done, then it will cause a <code>NullPointerException</code>.</li>
</ul>

<p>A better idea would be to simply propagate the exception, so that the caller will stop trying to process a <code>Document</code> that isn't there.</p>

<p>Furthermore, what does it mean to "prepare a connection"? It looks like this code goes way beyond preparing a connection â€” it actually makes the connection and fetches the content as a <code>Document</code>!</p>

<p>So, the class should look more like this:</p>

<pre><code>public class JSoupConnector {
    public static Document connect(String url) throws IOException {
        try {
            return Jsoup.connect(url).get();
        } catch (IOException e) {
            log.warn("Cannot connect to URL " + url);
            throw e;
        }
    }
}
</code></pre>

<p>At that point, this wrapper is hardly doing anything at all, and you might consider eliminating this helper functional altogether.</p>
    </div>