<div class="s-prose s-prose__disable-spoiler-hover js-post-body" itemprop="text">
<p>First, any <code>async</code> function should end with <code>Async</code>, ie <code>MyFunctionAsync</code>. You can see examples of this in the other <code>async</code> functions you're calling throughout your code.</p>
<p>As to your requirements, the exception you throw at the end is devoid of any useful information. It has no exception origination information (line number etc) and no correct stack trace. Either save the exception you're handling in the top <code>try</code> when it happens, or even better rethrow it on the spot.</p>
<p>I very much question your updating the item even though the first part errored out, so rethrowing the first set of exceptions on the spot is what I'd do, but if you want to update it even in an error case, bring the update function with you in the <code>catch</code> and then rethrow.</p>
<p>The second part is fine, you're rethrowing as you should.</p>
    </div>